services:
  - type: web
    name: scuibai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn scuibai.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: scuibai-db
          property: connectionString
      - key: DISABLE_COLLECTSTATIC
        value: "1"
      - key: CLOUD_NAME
        sync: false
      - key: API_KEY
        sync: false
      - key: API_SECRET
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: NEW_RESEND_API_KEY
        sync: false
      - key: NEW_CLIENT_ID
        sync: false
      - key: NEW_CLIENT_SECRET
        sync: false
      - key: SOCIAL_SECRET_KEY
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: PAYSTACK_SECRET_KEY
        sync: false
      - key: ALLOWED_HOSTS
        value: "scuibai.onrender.com"

databases:
  - name: scuibai-db
    plan: free
    databaseName: scuibai
    user: scuibai
