# Generated by Django 6.0.3 on 2026-08-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_ingestedjob_matchresult"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingestedjob",
            name="company",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="ingestedjob",
            name="location",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="ingestedjob",
            name="source_job_id",
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name="ingestedjob",
            name="title",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="jobs",
            name="location",
            field=models.CharField(max_length=1000),
        ),
    ]
