# Generated by Django 6.0.3 on 2026-08-23 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_ingestedjob_company_alter_ingestedjob_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="boostsubscription",
            name="auto_renew",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="UserCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("authorization_code", models.CharField(max_length=100)),
                ("card_type", models.CharField(blank=True, max_length=50, null=True)),
                ("last4", models.CharField(blank=True, max_length=4, null=True)),
                ("exp_month", models.CharField(blank=True, max_length=2, null=True)),
                ("exp_year", models.CharField(blank=True, max_length=4, null=True)),
                ("brand", models.CharField(blank=True, max_length=50, null=True)),
                ("bank", models.CharField(blank=True, max_length=100, null=True)),
                ("signature", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
