# Generated by Django 6.0.3 on 2026-10-04 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_boostsubscription_auto_renew_usercard"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingestedjob",
            name="application_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ingestedjob",
            name="posted_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
